<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AssemblyName>PortPilot.Mac</AssemblyName>
    <Version>1.1.0</Version>
    <PublishTrimmed>false</PublishTrimmed>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PortPilot.Core/PortPilot.Core.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
    <AvaloniaResource Include="../PortPilot/Resources/PortPilot.ico" Link="Assets/PortPilot.ico" />
  </ItemGroup>
</Project>
